input {
  tcp {
    port => 5045
    host => "0.0.0.0"
    codec => json_lines
    type => "wazuh-alerts"
  }
  beats {
    port => 5046
    host => "0.0.0.0"
    type => "wazuh-beats"
  }
}

filter {
  if [type] == "wazuh-alerts" {
    mutate {
      add_field => { "log_source" => "wazuh" }
    }
  }
}

output {
  if [type] == "wazuh-alerts" or [type] == "wazuh-beats" {
    elasticsearch {
      hosts => ["https://localhost:9200"]
      user => "elastic"
      password => "YOUR_ELASTIC_PASSWORD_HERE"
      ssl_enabled => true
      ssl_certificate_authorities => ["/etc/logstash/http_ca.crt"]
      index => "wazuh-alerts-%{+YYYY.MM.dd}"
    }
  }
}
