input {
  beats {
    port => 5044
    host => "0.0.0.0"
    type => "winlogbeat"
  }
}

filter {
  if [type] == "winlogbeat" {
    if [winlog][event_id] {
      mutate {
        add_field => { "sysmon_event_id" => "%{[winlog][event_id]}" }
      }
    }
    if [winlog][event_id] == 1 {
      mutate { add_tag => ["sysmon_process_create"] }
    }
    if [winlog][event_id] == 3 {
      mutate { add_tag => ["sysmon_network_connect"] }
    }
    if [winlog][event_id] == 10 {
      mutate { add_tag => ["sysmon_lsass_access"] }
    }
  }
}

output {
  if [type] == "winlogbeat" {
    elasticsearch {
      hosts => ["https://localhost:9200"]
      user => "elastic"
      password => "YOUR_ELASTIC_PASSWORD_HERE"
      ssl_enabled => true
      ssl_certificate_authorities => ["/etc/logstash/http_ca.crt"]
      index => "winlogbeat-%{+YYYY.MM.dd}"
    }
  }
}
